resources:
  - task-create-ephemeral-ns.yaml
  - task-delete-ephemeral-ns.yaml
  - task-dummy-test.yaml
  - task-setup-db.yaml
  - task-argocd-apply-database.yaml
  - task-argocd-apply-online-apps.yaml
  - task-argocd-delete.yaml
  - task-call-api-multi-data-entry.yaml
  - task-cleanup-complete-env.yaml
  - task-check-db-multi-assert.yaml
  - task-wait-for-online-readiness.yaml
  - task-argocd-apply-batch-apps.yaml
  - task-wait-for-job-completion.yaml
  - pipeline-manual-cleanup.yaml
  - pipeline-simple-test.yaml
  - pvc-efs.yaml
