resources:
  - task-create-ephemeral-ns.yaml
  - task-delete-ephemeral-ns.yaml
  - task-dummy-test.yaml
  - task-setup-db.yaml
  - task-argocd-apply-database.yaml
  - task-argocd-apply-online-apps.yaml
  - task-argocd-delete.yaml
  - pipeline-sample.yaml
  - pvc-efs.yaml
