apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sample-test-pipeline
spec:
  params:
    - name: test-id
      default: "test-001"
    - name: repo-url
      default: 'https://github.com/kforetas/scenario-test-demo.git'
      type: string
  workspaces:
    - name: shared-data
  
  tasks:
    - name: git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: main
        - name: DELETE_EXISTING
          value: 'true'
        - name: SUBDIRECTORY
          value: ""
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: "testcases/$(params.test-id)"
      workspaces:
        - name: output
          workspace: shared-data

    - name: setup-env
      runAfter: 
        - git-clone
      taskRef:
        name: create-ephemeral-ns
      params:
        - name: ns-name
          value: "demo-st-$(params.test-id)"

    #- name: run-pod-test
    #  runAfter: 
    #    - setup-env
    #  taskRef:
    #    name: dummy-system-test
    #  params:
    #    - name: target-ns
    #      value: "demo-st-$(params.test-id)"

    - name: deploy-database
      runAfter:
        - run-pod-test
      taskRef:
        name: argocd-apply-database
      params:
        - name: test-id
          value: "$(params.test-id)"

    - name: setup-database
      runAfter:
        - deploy-database
      taskRef:
        name: set-up-db
      params:
        - name: test-id
          value: "$(params.test-id)"
        - name: target-ns
          value: "demo-st-$(params.test-id)"
        - name: db-service-name
          value: "postgresql"
      workspaces:
        - name: source
          workspace: shared-data
  
    - name: deploy-online-apps
      runAfter:
        - setup-database
      taskRef:
        name: argocd-apply-online-apps
      params:
        - name: test-id
          value: "$(params.test-id)"

    # --- Custom Area --- #
    # Data Entry
    - name: data-entry-shopping
      runAfter:
        - deploy-online-apps
      taskRef:
        name: call-api-from-file
      params:
        - name: test-id
          value: $(params.test-id)
        - name: data-file-name
          value: "shopping_entry.yaml"
        - name: namespace-name
          value: "demo-st-$(params.test-id)"
      workspaces:
        - name: source
          workspace: shared-data

  finally:
    - name: delete-online-apps
      taskRef:
        name: argocd-delete-application
      params:
        - name: application-name
          value: "deploy-online-apps-demo-st-$(params.test-id)"
    
    - name: cleanup-database
      taskRef:
        name: argocd-delete-application
      params:
        - name: application-name
          value: "deploy-postgres-demo-st-$(params.test-id)"

    - name: cleanup-env
      taskRef:
        name: delete-ephemeral-ns
      params:
        - name: ns-name
          value: "demo-st-$(params.test-id)"
