apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sample-test-pipeline
spec:
  params:
    - name: test-id
      default: "test-001"
    - name: repo-url
      default: 'https://github.com/kforetas/scenario-test-demo.git'
      type: string
  workspaces:
    - name: shared-data
  
  tasks:
    # --- 準備フェーズ --- #
    # --- 01. 前掃除 (Pre-Cleanup) ---
    - name: pre-cleanup
      taskRef:
        name: cleanup-complete-env
      params:
        - name: test-id
          value: $(params.test-id)
    
    # --- 02. テストシナリオの取得 ---
    - name: git-clone
      runAfter: 
        - pre-cleanup
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: main
        - name: DELETE_EXISTING
          value: 'true'
        - name: SUBDIRECTORY
          value: ""
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: "testcases/$(params.test-id)"
      workspaces:
        - name: output
          workspace: shared-data

    # --- 環境構築フェーズ --- #
    # --- 03. NameSpace作成 ---
    - name: setup-env
      runAfter: 
        - git-clone
      taskRef:
        name: create-ephemeral-ns
      params:
        - name: ns-name
          value: "demo-st-$(params.test-id)"

    # --- 04. Database作成 ---
    - name: deploy-database
      runAfter:
        - setup-env
      taskRef:
        name: argocd-apply-database
      params:
        - name: test-id
          value: "$(params.test-id)"

    # --- 05. Databaseの初期データ設定 ---
    - name: setup-database
      runAfter:
        - deploy-database
      taskRef:
        name: set-up-db
      params:
        - name: test-id
          value: "$(params.test-id)"
        - name: target-ns
          value: "demo-st-$(params.test-id)"
        - name: db-service-name
          value: "postgresql"
      workspaces:
        - name: source
          workspace: shared-data
  
    # --- 06. オンラインアプリケーションの立ち上げ ---
    - name: deploy-online-apps
      runAfter:
        - setup-database
      taskRef:
        name: argocd-apply-online-apps
      params:
        - name: test-id
          value: "$(params.test-id)"

    # --- 07. オンラインアプリケーションの立ち上がり待ち ---
    - name: wait-online-ready
      runAfter:
        - deploy-online-apps
      taskRef:
        name: wait-for-online-readiness
      params:
        - name: test-id
          value: "$(params.test-id)"
        - name: namespace-name
          value: "demo-st-$(params.test-id)"
      workspaces:
        - name: source
          workspace: shared-data

    # --- テスト実施フェーズ --- #
    # --- 08. データ投入 ---
    #- name: data-entry-shopping
    #  runAfter:
    #    - deploy-online-apps
    #  taskRef:
    #    name: call-api-from-file
    #  params:
    #    - name: test-id
    #      value: $(params.test-id)
    #    - name: data-file-name
    #      value: "shopping_entry.yaml"
    #    - name: namespace-name
    #      value: "demo-st-$(params.test-id)"
    #  workspaces:
    #    - name: source
    #      workspace: shared-data
    
    # --- 09. バッチ処理実行 ---
    # --- 10. データ検証（Assert） ---
    - name: db-multi-assertion
      runAfter:
        - deploy-online-apps 
      taskRef:
        name: check-db-multi-assert
      params:
        - name: test-id
          value: $(params.test-id)
        - name: target-ns
          value: "demo-st-$(params.test-id)"
      workspaces:
        - name: source
          workspace: shared-data

  finally:
    # --- テスト完了フェーズ --- #
    # --- 11. レポート作成 ---
    # --- 12. 通知 ---
