apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: component-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/kforetas/scenario-test-demo.git'
    targetRevision: HEAD
    path: components
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tekton-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
