apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-namespace-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/kforetas/scenario-test-demo.git'
    targetRevision: HEAD
    path: namespaces
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
